### ISSUE TITLE
Docs : Miss the needed dependency vue-property-decorator

### ISSUE THREAD

**Issue by RomainBillot** [coddicat/vue-pinch-scroll-zoom#11]
Hi,

I got this error while trying to use your package:
```
This dependency was not found:

* vue-property-decorator in ./node_modules/@coddicat/vue-pinch-scroll-zoom/lib/index.esm.js
```

I'm adapting the package so it doesn't use `vue-property-decorator` but I think it's worth the mentioning in the documentation :)

Thanks !

**Comment by coddicat** [comment]
I will fix it in few days

**Comment by coddicat** [comment]
fixed by removing peerDependencies
