### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by ProXyTG** [coddicat/vue-pinch-scroll-zoom#13]
When vue3 support will be available :)

**Comment by coddicat** [comment]
@ProXyTG I am starting on it on 13 April, will be done in few days

**Comment by voratham** [comment]
@coddicat  
Sorry, I  implemented with migration to vue3 but i cut feature not unused, Can you consider my PR?
https://github.com/coddicat/vue-pinch-scroll-zoom/pull/14 (ed

**Comment by Anthelmed** [comment]
Any update on that?

**Comment by coddicat** [comment]
@Anthelmed 
please make a PR to https://github.com/coddicat/vue-pinch-scroll-zoom/tree/main_vue3 branch,
update package.json:
  "name": "@coddicat/vue3-pinch-scroll-zoom",
  "version": "0.1.0",

**Comment by ProXyTG** [comment]
Any updates or date when it will be ready? :)

**Comment by coddicat** [comment]
Done. Take a look I’ve published as @coddicat/vue3-pinch-scroll-zoom

вт, 3 трав. 2022 р. о 18:09 Branimir Bakula ***@***.***> пише:

**Comment by Anthelmeifs** [comment]
@coddicat Maybe I'm doing something wrong but I have this error after installing your plugin
"Failed to resolve entry for package "@coddicat/vue3-pinch-scroll-zoom". The package may have incorrect main/module/exports specified in its package.json."

**Comment by voratham** [comment]
> We open PR about issue, Please everyone help me review
@coddicat  
https://github.com/coddicat/vue-pinch-scroll-zoom/pull/15

**Comment by coddicat** [comment]
done and published
