### ISSUE TITLE
Width and Height are not reactive

### ISSUE THREAD

**Issue by jaybo** [coddicat/vue-pinch-scroll-zoom#17]
I'm using the Vue3 version and it looks like the width and height values are not reactive, so for example, I can't dynamically resize the zoomer in a responsive design app.  I guess I can understand this isn't an easy undertaking, but thought I'd save somebody a few hours trying to make it work.

```
 <PinchScrollZoom
    :width="item.slideSizeWidth"  // dynamically changing item.slideSizeWidth has no effect !!!
    :height="item.slideSizeHeight"
```

If one were to implement this feature, forcing a reset whenever the width or height changed would be a fine simplification.

**Comment by coddicat** [comment]
Hi, @jaybo if you still use this package I would like to update that I completely refactored it, now @coddicat/vue-pinch-scroll-zoom for vue3 and clearer

**Comment by AAAAsea** [comment]
> Hi, @jaybo if you still use this package I would like to update that I completely refactored it, now @coddicat/vue-pinch-scroll-zoom for vue3 and clearer

I came across the same problem, but my project is still based on Vue2. So is there any way to make the width or height reactive in Vue2?
