### ISSUE TITLE
How to disable scrolling and panning

### ISSUE THREAD

**Issue by theoreticalsampling** [coddicat/vue-pinch-scroll-zoom#18]
Hi,

I'm trying to find a way how to disable all scrolling and panning, while keeping the current transformation. Is that possible. And if so, can you tell me how to do that?

**Comment by coddicat** [comment]
@theoreticalsampling draggable and scale props?

**Comment by theoreticalsampling** [comment]
Hi, thanks for your reply! I just realized, I used the draggable prop wrong. At first I tried `draggable="false"` but it had no effect. I had to write `:draggable="false"` for it to work. But scale does not seem to have any effect. I tried both `:scale="2"`, and `scale="2"` but I am still able to scale the picture inside of the PinchScrollZoom-Widget.

**Comment by coddicat** [comment]
@theoreticalsampling use min-scale and max-scale properties
