### ISSUE TITLE
Off positioned cursor/touch origin

### ISSUE THREAD

**Issue by Bambalazs** [coddicat/vue-pinch-scroll-zoom#2]
Hi,

First of all, thanks for the neat plugin. You did a great job!

I noticed an annoying bug when the component is used in the right side of the window and you start scrolling to zoom which results in off positioned originX and originY. 

The possible solution could be using a ref for `div.pinch-scroll-zoom` and calculating the refs' absolute position with `.getBoundingClientRect().left` for horizontal axis and `.getBoundingClientRect().top` for vertical axis, then extracting these distances from originX and originY accordingly.

**Comment by coddicat** [comment]
> Hi,
> 
> First of all, thanks for the neat plugin. You did a great job!
> 
> I noticed an annoying bug when the component is used in the right side of the window and you start scrolling to zoom which results in off positioned originX and originY.
> 
> The possible solution could be using a ref for `div.pinch-scroll-zoom` and calculating the refs' absolute position with `.getBoundingClientRect().left` for horizontal axis and `.getBoundingClientRect().top` for vertical axis, then extracting these distances from originX and originY accordingly.

Thanks for reporting the bug. 
The bug has been fixed and closed - https://github.com/coddicat/vue-pinch-scroll-zoom/commit/2fc1c0e9d352f49f7eaf5652cecce64c1357f399.
