### ISSUE TITLE
Failed to resolve entry for package...

### ISSUE THREAD

**Issue by skmbr** [coddicat/vue-pinch-scroll-zoom#22]
I get the following error when I try to use this in my app:

`Failed to resolve entry for package "@coddicat/vue-pinch-scroll-zoom". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@coddicat/vue-pinch-scroll-zoom". The package may have incorrect main/module/exports specified in its package.json.`

Am I missing something obvious?  It's a vue 3 / Quasar 2 app and the component I'm importing into used the options API if that's relevant?

This occurs even in this simple component:

```
<template>

  <PinchScrollZoom>
    <img src="/test.png"/>
  </PinchScrollZoom>

</template>


<script setup>
import PinchScrollZoom from '@coddicat/vue-pinch-scroll-zoom'
</script>
```

Any help greatly appreciated as this looks like just what I've been looking for to replace PinchZoom.js! :)

**Comment by coddicat** [comment]
@skmbr thanks, i am looking right now

**Comment by skmbr** [comment]
Thank you!

**Comment by coddicat** [comment]
@skmbr fixed, I have just updated package. plz install the newest 4.2.2, and let me know if it works?

**Comment by coddicat** [comment]
@skmbr and plz note that you need to set
  :width="…"
  :height="…"
These required properties

**Comment by skmbr** [comment]
Ok... that sorted the original error, now I get this in the console:

![image](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/1945312/7584d483-9e58-4958-95cc-da9e8ce3dc1e)

**Comment by coddicat** [comment]
@skmbr Please provide your code

**Comment by skmbr** [comment]
As in my original post, but with height and width added:

```
<template>

  <PinchScrollZoom width="200" height="200">
    <img src="/test.png"/>
  </PinchScrollZoom>

</template>


<script setup>
import PinchScrollZoom from '@coddicat/vue-pinch-scroll-zoom'
</script>
```

**Comment by skmbr** [comment]
If I replace my main App.vue with the above code I get slightly less errors:

![image](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/1945312/b6e4533f-50bb-42e6-b34a-4222d5ed8eb8)

**Comment by coddicat** [comment]
I mean - how do you use your component? 
where did you put it? If you can provide your entire project it will be easier to figure out

**Comment by skmbr** [comment]
Can't share the entire project, but I'll try and spin up a new Quasar project tomorrow and see if it still does it with that!

**Comment by skmbr** [comment]
So I can't say I exactly understand this, but with the help of this SO post...

https://stackoverflow.com/questions/71063992/when-importing-self-made-vue-3-library-into-vue-3-project-uncaught-typeerror

... and setting this in my Vite config:

viteConf.resolve.dedupe = ['vue']

I do now have it working! 🥳
