### ISSUE TITLE
Impossible to get back to scale = 1 with mousewheel if min-scale = 1

### ISSUE THREAD

**Issue by jeanfrancoisgb** [coddicat/vue-pinch-scroll-zoom#24]
Hi, 

I have set min-scale to 1 and max-scale to 3. I can zoom with the mouse wheel and it works well, but then when I unzoom with the mouse wheel, it can't get back precisely to the 1.0 scale (min-value), it remains a little bit bigger.

If I zoom and unzoom many times with mouse wheel I can get close to the 1.0 scale but never exactly it. Playing with the wheel-velocity helps a little and allows me to get closer ton min-scale, but does not fix the issue.

It's problematic because it leaves room for a vertical scroll even when the content is same height as the viewer.

Thank you for the great package, it's very useful. If you have a buymeacoffeelink I'd send a lil something for sure.

I have other less important issues that I might post here soon, I try to gather more informations.

Have a good day!

**Comment by coddicat** [comment]
@jeanfrancoisgb hi, I will fix the bug in 2 days

**Comment by jeanfrancoisgb** [comment]
Hi! Any update? 

I can do it and do a pull request if you prefer?

**Comment by jeanfrancoisgb** [comment]
Also just tested, same issue happend with pinch dezoom on a touch screen.

**Comment by coddicat** [comment]
@jeanfrancoisgb tomorrow i am going  to fix and close

**Comment by coddicat** [comment]
@jeanfrancoisgb fixed and published, "version": "4.2.4". Please open and describe another bug for same issue happens with pinch dezoom on a touch screen you mentioned above
