### ISSUE TITLE
Looking for a way to programatically change the scale and respecting the context/within parameter (zoom/unzoom buttons)

### ISSUE THREAD

**Issue by jeanfrancoisgb** [coddicat/vue-pinch-scroll-zoom#25]
Hi,

I'm desperate in trying to find a way to zoom in and zoom out (while respecting the max and min scale set) by pushing on a + ou - button.

Right now I'm using this:

```
zoomer.value?.setData({
    scale: newScale,
    originX: state.originX,
    originY: state.originY,
    translateX: state.translateX,
    translateY: state.translateY,
  })
```

newScale is set with a value withing my min and max scale and it works but not in a logic way. 

I'm trying to zoom in the middle and unzoom from the middle, just like if I mousewheeled from the center but on the click on a + or - button. Also, with the method I use now, if I unzoom but I was watching the upper part of content, the content gets out of bound as the scale reduce, until I drag the content, then the "within" context is respected and the content gets back to a good position.

One solution could be to add accessible method to allow setting the scale (and scale from middle), but it would then process like a mousewheel event for content positions?

As last time, I'm ok to contribute or sponsor this plugin, with buymeacoffee or anything else. Let me know! 🙂

I can also provide video if needed.

Thank you!

**Comment by coddicat** [comment]
@jeanfrancoisgb Hi, thanks for reaching out. I'll work on adding this feature over the upcoming weekend. If you have any additional requests, I will definitely try to include them as well.

**Comment by jeanfrancoisgb** [comment]
That's very generous of you, I appreciate your commitment and responsiveness about your package, it is very useful to me. Thank you again and again.

I'm building kind of a magazine reader with it, there would be nice things to have for you if you have time and desire:
- a way to paginate content; my content is very large, but consists of multiple divs horizontally, a method that auto moves to the previous/next closest block would be amazing. I think it could be useful to many people (people making image gallery too) but definitely not everyone I guess though.


Thank you again!

**Comment by coddicat** [comment]
@jeanfrancoisgb Hi, I have just finished the implementation of this new feature, please read change log and readme....
to add key actions just add prop 'key-actions' and for initially centralize the image add  prop 'centred'
let me know if it works well and if you would like another features

**Comment by jeanfrancoisgb** [comment]
Hi @coddicat 

Thank you so so much, can't wait to test it.

I have trouble updating the package, even when I remove my node_modules and reinstall, the node_modules\@coddicat\vue-pinch-scroll-zoom folder only contains README.md and the package.json.

Because all other packages seems to work ok, I'm not sure it's on my side, but I'm trying to find the issue and keep you updated.

**Comment by jeanfrancoisgb** [comment]
I confirm you there is only 2 files in the new version: https://www.npmjs.com/package/@coddicat/vue-pinch-scroll-zoom

![Screenshot - 2023-11-27T120420 933](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/4010302/51505a6d-22a0-441b-b5bf-62102c3f3b9c)

**Comment by coddicat** [comment]
@jeanfrancoisgb oops, fixed, please check it

**Comment by coddicat** [comment]
@jeanfrancoisgb #24 -  you'r right - just fixed, please update version
manualZoom() - works relatively to the current scale value, so if the current scale is 2 and execute .manualZoom(2) the new scale value will be 4. but if you need to scale to a concrete value run 
```ts
  const newState = zoomer.value.setData({
    scale: 1
  });
  mapStateProps(newState);
```
let me know if now it works

**Comment by jeanfrancoisgb** [comment]
Ok I tested more, I could make it work once, only if I zoomed just a little bit with the mousewheel at least one before clicking the zoom button. But then I can't unzoom or zoom, or even drag/move with mouse.

**Comment by coddicat** [comment]
don't set null values, use undefined instead, send me the link to fiddler I will try investigate your issues

**Comment by jeanfrancoisgb** [comment]
The package sets values at NaN after I use manualZoom method like provided code.

I will prepare a Fiddle, I get back to your really soon. Thank you!

**Comment by jeanfrancoisgb** [comment]
I could not use CodeSandbox or FiddleJS because of imports structure so I made a public test repo that you can use https://github.com/jeanfrancoisgb/demo-pinch

Just npm run dev.

You can try Zoom + and Zoom - buttons. Events are shown in the js console.

Whatever the situation, the only way I could make it work was if I prezoom manually a little  bit, then press Zoom +, then nothing works anymore, scale and other values are lost. Even then, it doesn't zoom as if cursor was in middle.

Let me know if you need anything else. Thanks again!

**Comment by coddicat** [comment]
I got it,
There is a discrepancy in the method implementation compared to the method signatures described in the README, specifically regarding the parameter types. The correct approach is to pass the parameters directly, not as objects. 
For example:
```ts
function zoom() {
  zoomer.value?.manualZoom(1.5);
}

function unzoom() {
  zoomer.value?.manualZoom(0.5);
}
```
Also, please note that the value passed is a scaling factor. Passing 1 will have no effect. To scale up, the value should be greater than 1, and to scale down, it should be less than 1 (but not negative)

**Comment by jeanfrancoisgb** [comment]
Great, I'll test again tomorrow with the good values. Thank you very much for you time. 

I think it would be nice to have a setScale() method as well. If we use the reset one, we need to specify all the other properties as well, making it very hard to be used as zoom method. If setscale receives a value smaller than minscale, then minscale is set as scale. And opposite for maxScale. And zooming/dezooming from middle as well?

I can live without that, but it would be a nice luxury! 😊

In all cases, thank you again, I'll confirm and close tomorrow after testing.

**Comment by coddicat** [comment]
@jeanfrancoisgb you don't need to provide all the values in setData function, it's allowed undefined - setData({ scale: 1 })
