### ISSUE TITLE
The `setData` method does not respect `within` props

### ISSUE THREAD

**Issue by jongmin4943** [coddicat/vue-pinch-scroll-zoom#29]
Hi, thanks for making this awesome library.

I've been struggling to use the `setData` method with `within` props.
If `setData` method gets `translateX` or `translateY` value that larger than container size, `within` feature does not work.

[reproduction](https://stackblitz.com/edit/github-e5kkou?file=nuxt.config.ts,app.vue)

if u press the `test` button, u will see what I mean

**Comment by coddicat** [comment]
@jongmin4943 thanks for reporting.
Tomorrow will be a new version with the fix

**Comment by jongmin4943** [comment]
I've got another suggestion @coddicat. What do u think if `containerStyle` has `transform : translate3d() scale()` instead of `transform : translate() scale()` to push CSS animations into hardware acceleration for better perf?
```typescript
const containerStyle = computed(() => {
  const x = `${state.axisX.point}px`;
  const y = `${state.axisY.point}px`;
  const translate = `translate3d(${x}, ${y}, 0) scale(${state.currentScale})`;
  const transformOrigin = `${state.axisX.origin}px ${state.axisY.origin}px`;

  return {
    transform: translate,
    'transform-origin': transformOrigin
  };
});
```
something like this

**Comment by coddicat** [comment]
I will test and apply it tomorrow, thanks for advice

**Comment by jongmin4943** [comment]
It works like a charm! Thanks!
