### ISSUE TITLE
Failed to resolve entry for package in 4.5.0

### ISSUE THREAD

**Issue by Krystus** [coddicat/vue-pinch-scroll-zoom#35]
[plugin:vite:import-analysis] Failed to resolve entry for package "@coddicat/vue-pinch-scroll-zoom". The package may have incorrect main/module/exports specified in its package.json.

Error after npm update.

**Comment by coddicat** [comment]
@Krystus thank you very much, the bug has been fixed, please upgrade to 4.6.0
