### ISSUE TITLE
One finger scroll on phones & tablets

### ISSUE THREAD

**Issue by AlvaroMartinezQ** [coddicat/vue-pinch-scroll-zoom#43]
I'm currently using this library to display an image on a mobile test app I'm developing. Sometimes the images that I render are too large and the text below them is not displayed unless you scroll down on the device. Right now I need to scroll next to the limits of the screen because the image does not allow 1 finger scroll when you scroll down on it.

Is it possible to scroll down/up when putting only one finger over the image?

Thanks in advance! 😃

**Comment by qq7** [comment]
@AlvaroMartinezQ https://github.com/coddicat/vue-pinch-scroll-zoom/issues/42
see if this works for you

**Comment by AlvaroMartinezQ** [comment]
Hi @qq7 we tested but unfortunately did not work. We did find this css class, https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action#pan-y, which made the trick 😃
