### ISSUE TITLE
Component overwrites default right-click behaviour of images

### ISSUE THREAD

**Issue by ShadowSpade** [coddicat/vue-pinch-scroll-zoom#9]
When using the component (which I love by the way, thanks) the default browser options are no longer available: 
![image](https://user-images.githubusercontent.com/67732805/148899951-0a370355-a9d0-4025-b3d7-3f3f51eee734.png)
 instead of 
![image](https://user-images.githubusercontent.com/67732805/148899969-56045bb2-4b46-4ab7-a736-601233084c19.png)

Is there any way I can get the default behaviour back? Our clients need to download images

**Comment by coddicat** [comment]
@ShadowSpade next week I will try to fix it

**Comment by ShadowSpade** [comment]
> @ShadowSpade next week I will try to fix it

Thank you so much! Much appreciated

**Comment by coddicat** [comment]
fixed: https://github.com/coddicat/vue-pinch-scroll-zoom/pull/10

**Comment by ShadowSpade** [comment]
Dude you are the best. Thank you so much!
